version: "3"
services:
  task:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/code
    restart: always
  elasticsearch:
    image: elasticsearch:6.8.4
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
